# ! Do not run it on production development server !

version: '3'

volumes:
  pg_data:
  static:

services:

    # Postgres container
    db:
        image: postgres:13.10
        env_file: .env
        volumes:
            - pg_data:/var/lib/postgresql/data


    # Django backend container
    backend:
        build: ./backend/
        env_file: .env
        volumes:
            - static:/backend_static
        depends_on:
            - db


    # React frontend container
    frontend:
        env_file: .env
        build: ./frontend/
        # copy static files in volume relates folder
        command: cp -r /app/build/. /frontend_static/
        volumes:
            - static:/frontend_static


    # Nginx container
    gateway:
        build: ./gateway
        env_file: .env
        volumes:
            - static:/staticfiles/
        ports:
            - 8000:80
